[DNM] Squash of lineage-17.1-android-10.0.0_r31
Squashed commit of the following:

commit a87a938d2d3b451115a108c17e6d322d6f477fde
Merge: 596d32ec9 f0fe2de59
Author: android-build-team Robot <android-build-team-robot@google.com>
Date:   Wed Jan 1 02:16:23 2020 +0000

    Snap for 6105141 from f0fe2de594d0040ae3f5ddda9f3c16c5b465ef92 to qt-qpr2-release

    Change-Id: I695deeb4289238a8a25cb29d0a264bcdb91e45e3

commit f0fe2de594d0040ae3f5ddda9f3c16c5b465ef92
Author: Bill Yi <byi@google.com>
Date:   Mon Dec 30 21:34:13 2019 -0800

    Import translations. DO NOT MERGE

    Change-Id: I871c992a16f031d2ad54edef540391a3a083b456
    Auto-generated-cl: translation import

commit 596d32ec9ef5659486f7c14720163f359ebf1403
Merge: a357a5ce5 edee43aaf
Author: android-build-team Robot <android-build-team-robot@google.com>
Date:   Sat Dec 21 02:08:42 2019 +0000

    Snap for 6091187 from edee43aaf41894b7ce520011cffbc60f2ecb53e6 to qt-qpr2-release

    Change-Id: Ibc7f26f934e10d32f58f2a697a3f97774521b968

commit edee43aaf41894b7ce520011cffbc60f2ecb53e6
Merge: c88aae2d9 4338eab49
Author: Weichin Weng <weichinweng@google.com>
Date:   Fri Dec 20 08:38:01 2019 +0000

    Merge "DO NOT MERGE: Make NIAP a Global Setting toggle." into qt-qpr1-dev

commit a357a5ce55edc8b0e52062059b27c2bdf02152ef
Merge: bf1627016 c88aae2d9
Author: android-build-team Robot <android-build-team-robot@google.com>
Date:   Thu Dec 19 08:07:56 2019 +0000

    Snap for 6085360 from c88aae2d9edbf1dbb896bd3595ea25889f29a016 to qt-qpr2-release

    Change-Id: I1e8dba3d01adb9786c048a90a81dd5844c3c3ac4

commit c88aae2d9edbf1dbb896bd3595ea25889f29a016
Merge: 2b0e75626 e7f502117
Author: TreeHugger Robot <treehugger-gerrit@google.com>
Date:   Thu Dec 19 03:57:43 2019 +0000

    Merge changes from topic "gps no sound" into qt-qpr1-dev

    * changes:
      Update playback state only for navigation sound
      Monitor AudioManger Playback state to update the AVRCP playback state

commit e7f50211780183985d7093125b06d4a67f5c7461
Author: Ted Wang <tedwang@google.com>
Date:   Wed Nov 6 00:46:27 2019 +0800

    Update playback state only for navigation sound

    Update playback status for all system sound might confuse carkit. Now
    only update playback status for navigation sound.

    Test: test with carkit
    Bug: 143897897
    Bug: 138249637
    Merged-In: I1c3882879d6576b7c1d9277acdd18d720529d3d6
    Change-Id: I1c3882879d6576b7c1d9277acdd18d720529d3d6

commit a07c05e2e0351e07cf08db187cf5e0553c697dff
Author: Ted Wang <tedwang@google.com>
Date:   Wed Jun 19 14:24:55 2019 +0800

    Monitor AudioManger Playback state to update the AVRCP playback state

    Some carkit won't play A2DP audio when AVRCP playback state is paused.
    Causing navigation sound not able to heard from carkit speaker if there
    is not music playing.
    Add registration for onPlaybackConfigChanged can helps to monitor if
    there is any audio playback is active, So AVRCP can report correct
    playback state to remote to play the audio playback.
    Some additonal rules when updating playback state:
    - Do not update audio playback state when there is media player playing.
    This is to prevent send playback state paused when audio playback and
    media player are playing at same time and audio playback stop first.
    - Update playback status of acitve media player when audio playbac stop playing
    and there is not media player playing.

    Bug: 128982202
    Bug: 138249637
    Test: atest BluetoothInstrumentationTests
    Merged-In: I8f28a7eb0c3f923c656c889375c660b38d9e6236
    Change-Id: I8f28a7eb0c3f923c656c889375c660b38d9e6236

commit 2b0e75626a17ad3162af591525fbe3c7707b52fe
Author: jonerlin <jonerlin@google.com>
Date:   Mon Nov 25 22:47:00 2019 +0800

    A2dp: Check the value of mConnectionState in isConnected

    * There could be potential critical timing to cause
    java.lang.ArrayIndexOutOfBoundsException: index=-1, when a2dp state machine
    exit one state to enter another state. at this timing, the mStateStackTopIndex
    value of mStateStack be set to -1.
    * Checking mConnectionState value which maintained in A2dpStateMachine to avoid
    this AndroidRuntime exception.

    Bug: 142217033
    Test: Enable Bluetooth -> Connect Bluetooth headset -> Disconnect
    Bluetooth headset -> Disable Bluetooth then check a2dp state machine log.
    Change-Id: Ifdd3e96b84496cef04a70d95b5b64eca81e5db9c

commit 4338eab49bcdb36632b0e0cb6b099b6c7d0da127
Author: Martin Brabham <optedoblivion@google.com>
Date:   Thu Nov 7 12:24:35 2019 -0800

    DO NOT MERGE: Make NIAP a Global Setting toggle.

    Make the NIAP mode a Global toggle that can be modified by ADB for Enterprise provisioning.

    Bug: 140483038
    Test: atest net_test_bluetooth
    Change-Id: Ia508fbd99cb39d45e2a66e071e69617575f34f02
    Merged-In: Ia508fbd99cb39d45e2a66e071e69617575f34f02
    (cherry picked from commit 1622cfb8fbc8b8735188ba7541b07c1a491ff753)

commit bf1627016357e94a1309d81c62dacc1ab3456df6
Merge: a229b78ef fc62052d3
Author: android-build-team Robot <android-build-team-robot@google.com>
Date:   Sat Dec 14 02:17:51 2019 +0000

    Snap for 6072377 from fc62052d3446475a045ee533e0b6dcec1eff8109 to qt-qpr2-release

    Change-Id: I0d3d17e575a2ae00083ca3a3cb95c978b4d9ad03

commit fc62052d3446475a045ee533e0b6dcec1eff8109
Merge: d940f9287 b46f4f570
Author: Automerger Merge Worker <android-build-automerger-merge-worker@system.gserviceaccount.com>
Date:   Fri Dec 13 19:30:23 2019 +0000

    Enforce BLUETOOTH_PRIVILEGED in setPhonebookAccessPermission am: 8d1e8979f5 am: b46f4f570a

    Change-Id: I3fbbc7572616349b1f13a6c8dab584ebd109850d

commit b46f4f570afcced7364fc3706088afade31a641e
Merge: 7e9fbcc75 8d1e8979f
Author: Automerger Merge Worker <android-build-automerger-merge-worker@system.gserviceaccount.com>
Date:   Fri Dec 13 19:11:35 2019 +0000

    Enforce BLUETOOTH_PRIVILEGED in setPhonebookAccessPermission am: 8d1e8979f5

    Change-Id: Id6c56ba973310696b654be85accff6a4d8a5d4b2

commit d940f9287b435733ac5be9b1a7ece3bd0ec015ed
Merge: 0f4d4806e e775cb81e
Author: TreeHugger Robot <treehugger-gerrit@google.com>
Date:   Fri Dec 13 17:17:10 2019 +0000

    Merge "Send call state to native when silence mode is on" into qt-qpr1-dev

commit e775cb81ed414fa114905384d14ac781b014007c
Author: Ugo Yu <ugoyu@google.com>
Date:   Thu Dec 12 21:45:53 2019 +0800

    Send call state to native when silence mode is on

    Partially blocking call state sometimes violating Handsfree
    profile spec, e.g. when silence state changes while MO/MT
    call is ringing. We have to remove this before we have a
    better solution.

    Bug: 145722028
    Test: Manual

    Change-Id: I89231dcb401d87c1692a09640b15d5fddc560912

commit 8d1e8979f56acfe477bd3b84994a716a8391a8eb
Author: Hansong Zhang <hsz@google.com>
Date:   Thu Dec 12 11:03:14 2019 -0800

    Enforce BLUETOOTH_PRIVILEGED in setPhonebookAccessPermission

    Bug: 145130871
    Test: POC
    Merged-In: Ib4985e18de9f6695acc371da78deb240d42671f1
    Change-Id: I3b8897166e223179fcbcf8c7a64e0c4d4ca974ef

commit a229b78efd48111a7300acce85f16cfa8290eaf2
Merge: cbc65fc95 0f4d4806e
Author: android-build-team Robot <android-build-team-robot@google.com>
Date:   Thu Dec 5 02:15:25 2019 +0000

    Snap for 6049975 from 0f4d4806e45ea000a37dbd517df4aaf3a3831bc8 to qt-qpr2-release

    Change-Id: I9aa82532e21041804b4802b94520708e773fbf50

commit 0f4d4806e45ea000a37dbd517df4aaf3a3831bc8
Author: Bill Yi <byi@google.com>
Date:   Wed Dec 4 06:06:23 2019 -0800

    Import translations. DO NOT MERGE

    Change-Id: I7ec1293ffb7357ea54ce5939fb7123b8326b2977
    Auto-generated-cl: translation import

commit cbc65fc9518f9af7af1bf45a17a711b8d6f72c51
Merge: e848848f5 9f8c12541
Author: android-build-team Robot <android-build-team-robot@google.com>
Date:   Wed Nov 27 02:03:36 2019 +0000

    Snap for 6034952 from 9f8c12541e16953cb3cc8952e5c1b9e29a87b2e8 to qt-qpr2-release

    Change-Id: I7e916fe4f1695566d3d9d5a81cf17a64d3e9ed1e

commit 9f8c12541e16953cb3cc8952e5c1b9e29a87b2e8
Author: Bill Yi <byi@google.com>
Date:   Sat Nov 23 20:24:39 2019 -0800

    Import translations. DO NOT MERGE

    Change-Id: Ib1aa6d94d468e4179f1f9ae67a289f32b944028d
    Auto-generated-cl: translation import

commit e848848f5ae18e16842e12f4cbcc73103db4db30
Merge: 4640bb3cb 893657b9a
Author: android-build-team Robot <android-build-team-robot@google.com>
Date:   Sun Nov 24 00:22:02 2019 +0000

    Snap for 6029402 from 893657b9ad6b72940605a8e598a092cb8d718b03 to qt-qpr2-release

    Change-Id: Ib8bdba548f279e643a166c004a33a87b3904a844

commit 893657b9ad6b72940605a8e598a092cb8d718b03
Author: weichinweng <weichinweng@google.com>
Date:   Thu Nov 14 01:45:47 2019 +0800

    BLE: GattService debug infomation implementation

    Implement GattService debug information.

    Bug: 140842714
    Test: adb shell dumpsys bluetooth_manager
    Change-Id: I8c707873d40edf3e50004aebf10c7104e0b2f745
    Merged-In: I8c707873d40edf3e50004aebf10c7104e0b2f745

commit 4c20828ce3ec053cf9021c17bee99e97455bd708
Author: weichinweng <weichinweng@google.com>
Date:   Thu Nov 14 01:10:54 2019 +0800

    BLE: Rename existing variables in AppScanStats

    rename existing variables.

    Bug: 140842714
    Test: adb shell dumpsys bluetooth_manager
    Change-Id: I3497a59e9ed80d09ebeb444027a8210e27195f92
    Merged-In: I3497a59e9ed80d09ebeb444027a8210e27195f92

commit 4640bb3cbf2c103e7225602e64ea36a0fbc6ad12
Merge: 63ef1ff4e f01e15d57
Author: android-build-team Robot <android-build-team-robot@google.com>
Date:   Thu Nov 14 02:12:15 2019 +0000

    Snap for 6006841 from f01e15d5782cddf91aa8bc65c32018a43a342f8d to qt-qpr2-release

    Change-Id: I4d6306b92f7d0fefa23e76dbb141ff5710996e32

commit f01e15d5782cddf91aa8bc65c32018a43a342f8d
Merge: 6f3c5b7a7 cc7ae8033
Author: TreeHugger Robot <treehugger-gerrit@google.com>
Date:   Wed Nov 13 02:48:43 2019 +0000

    Merge "Apply the new A2DP codec config only when passed the check with codec status" into qt-qpr1-dev

commit 63ef1ff4e0a35a6f7d0b2851687dc97511f45c62
Merge: 46af0c2a4 6f3c5b7a7
Author: android-build-team Robot <android-build-team-robot@google.com>
Date:   Wed Nov 13 02:15:04 2019 +0000

    Snap for 6004191 from 6f3c5b7a7ed3489948816de2149b304c13e227f9 to qt-qpr2-release

    Change-Id: I14890437b60c7df8b1a2ca3582248d7e22096d11

commit 6f3c5b7a7ed3489948816de2149b304c13e227f9
Merge: d97d82bae b4e7d6852
Author: TreeHugger Robot <treehugger-gerrit@google.com>
Date:   Tue Nov 12 07:49:35 2019 +0000

    Merge "BLE: Don't start scan if the same Pi scan is running." into qt-qpr1-dev

commit 46af0c2a48d100348a11ced3ef6476103c279dc2
Merge: 9c0f2aeda d97d82bae
Author: android-build-team Robot <android-build-team-robot@google.com>
Date:   Sun Nov 10 00:12:39 2019 +0000

    Snap for 5998981 from d97d82bae35d13491c07143c99b837af8e8dc759 to qt-qpr2-release

    Change-Id: I3f963084f55f741f6a84fb8b2c89e1616845630a

commit d97d82bae35d13491c07143c99b837af8e8dc759
Author: Bill Yi <byi@google.com>
Date:   Sat Nov 9 01:51:26 2019 -0800

    Import translations. DO NOT MERGE

    Change-Id: Ib3579aae1d3938ef28dd7d65021a76c42c7b189b
    Auto-generated-cl: translation import

commit b4e7d6852656e9dd90547d27c88025e090ce7777
Author: weichinweng <weichinweng@google.com>
Date:   Wed Oct 30 14:11:59 2019 +0800

    BLE: Don't start scan if the same Pi scan is running.

    For some APP, will trigger pending intent BLE scan when the APP start
    but doesn't stop pending intent BLE scan. After long time, it will use
    more client_if cause BLE scan leak. For the use case, don't start
    pending intent BLE scan if the same scan is running.

    Bug: 143014582
    Test: Trigger two or more Pi BLE scan with same intent information.

    Change-Id: Id032025e1276cd87626bd81e235078820948d909
    Merged-In: Id032025e1276cd87626bd81e235078820948d909

commit 9c0f2aeda056392ab1444b835aa071d0b901989e
Merge: 671cea218 f9128dcf0
Author: android-build-team Robot <android-build-team-robot@google.com>
Date:   Mon Oct 21 22:39:20 2019 +0000

    Snap for 5956190 from f9128dcf0251f491b8d58ad6ca947c362d2d9d49 to qt-qpr2-release

    Change-Id: Ia3693a6c01b511374116c4605288c6e36939db53

commit 671cea2184ff3eefd3d7f6e7335e5104bcdd33e6
Merge: 2aae2aefa 4a3a2fed6
Author: android-build-team Robot <android-build-team-robot@google.com>
Date:   Thu Oct 17 01:14:28 2019 +0000

    Snap for 5945193 from 4a3a2fed646019f590b39050a214cfbfc101fae1 to qt-qpr2-release

    Change-Id: I6a81b4ce8b0a68f26d96dca55097e94c41257cdc

commit f9128dcf0251f491b8d58ad6ca947c362d2d9d49
Author: Pavel Maltsev <pavelm@google.com>
Date:   Mon Oct 14 12:12:14 2019 -0700

    Ignore incoming A2DP if profile is disabled

    If profile was disabled (PRIORITY_OFF), it should not accept
    incoming connections. A2DP source currently respects priority off, in
    A2dpService.isOkToConnect(), but A2DP sink silently accepts incoming
    connection.

    Bug: 140590407
    Test: connect phone with Automotive OS (it implements sink
    profile). Disable A2DP from settings in Automotive OS, try to
    connect from the phone side - verify A2DP remains disconnected.

    Change-Id: Ib0afdd9436301ca1d76bb37ec871c4f974f1996f
    (cherry picked from commit 9be95315eb5e502889e7d49fadbc243bde2aba76)

commit 4a3a2fed646019f590b39050a214cfbfc101fae1
Author: Andrew Cheng <chengca@google.com>
Date:   Thu Oct 10 15:19:46 2019 -0700

    NullPointerException handling, connectObexSession

    In connectObexSession, if a null mSocket is passed to
    BluetoothObexTransport, then a NullPointerException will be thrown when
    a new ClientSession is created.

    This can occur if abort() --> closeSocket() is called between the calls
    to connectSocket() and connectObexSession().

    Bug: 142056980
    Test: cycle Bluetooth adapter on/off 1k times
    Change-Id: I78691eb03cd4f3e12922a31b1bc4f4144353c125

commit cc7ae80335c75da861477c2cf9e5e71836f41fd9
Author: Cheney Ni <cheneyni@google.com>
Date:   Tue Jun 11 22:38:54 2019 +0800

    Apply the new A2DP codec config only when passed the check with codec status

    In order to apply a new codec config, the Bluetooth framework needs to
    re-configure A2DP with remote, to restart the session with the Audio
    HAL, and to notify the audio server to reset the output. This is a
    heavy task over HALs and frameworks, so we use the current codec status
    to ignore redundant codec preferences.

    * To change the preference of optional codecs only when there are all
      mandatory and optional codecs selectable.
    * To apply the new codec preference only when those feeding parameters
      or codec specifics are changing.
    * Using the current feeding parameters as default settings, and no
      codec changed is needed.

    Bug: 131147224
    Bug: 133719424
    Test: atest -t BluetoothInstrumentationTests:com.android.bluetooth.a2dp
    Change-Id: I028b9f168d2e629dd02c8474592e3713445a5000
    Merged-In: I028b9f168d2e629dd02c8474592e3713445a5000
    (cherry picked from commit 1e2b5beb5c3c7fad890ad03dc96ef9415bebba83)

Change-Id: I08e99783549eea3a79fef3d67703896ab9986491