Bluetooth: Fix NPE on A2DP headset connect due to new codecs
A2dpCodecConfig.assignCodecConfigPriorities() returns an array of
length BluetoothCodecConfig.SOURCE_CODEC_TYPE_MAX but always populates
exactly 5 of those entries. This change prevents the following NPE if
BluetoothCodecConfig.SOURCE_CODEC_TYPE_MAX is ever increased to
accommodate new codecs:

    java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.bluetooth.BluetoothCodecConfig.isMandatoryCodec()' on a null object reference
           at com.android.bluetooth.a2dp.A2dpCodecConfig.disableOptionalCodecs(A2dpCodecConfig.java:131)
           at com.android.bluetooth.a2dp.A2dpService.disableOptionalCodecs(A2dpService.java:793)
           at com.android.bluetooth.a2dp.A2dpService.updateOptionalCodecsSupport(A2dpService.java:1074)
           at com.android.bluetooth.a2dp.A2dpStateMachine$Connected.enter(A2dpStateMachine.java:474)
           at com.android.internal.util.StateMachine$SmHandler.invokeEnterMethods(StateMachine.java:1037)
           at com.android.internal.util.StateMachine$SmHandler.performTransitions(StateMachine.java:879)
           at com.android.internal.util.StateMachine$SmHandler.handleMessage(StateMachine.java:819)
           at android.os.Handler.dispatchMessage(Handler.java:107)
           at android.os.Looper.loop(Looper.java:214)
           at android.os.HandlerThread.run(HandlerThread.java:67)

Change-Id: I6a552319de5bc46043956bb469cdce26f290c04a