Update patch set 2
Patch Set 2:

This breaks the ability to build Bluetooth.apk separately by running 'make Bluetooth' for some reason.

packages/apps/Bluetooth/src/com/android/bluetooth/map/BluetoothMasObexServer.java:1038: cannot find symbol
symbol  : method noEndofBody()
location: interface javax.obex.Operation
            op.noEndofBody();
              ^

Patch-set: 2